[package]
name = "cstr"
version = "0.1.3"
authors = ["Xidorn Quan <me@upsuper.org>"]
description = "Macro for building static CStr reference"
repository = "https://github.com/upsuper/cstr"
license = "MIT"
keywords = ["macro", "cstr"]

[dependencies]
cstr-macros = {path = "./macros", version = "0.1.3"}
procedural-masquerade = "0.1"
